# CKAN Frontend 
apiVersion: v1
kind: Pod
metadata:
  name: ckan-permission-setup 
  namespace: ckan
spec:
  containers:
  - name: ckan-permission-setup 
    image: cityofcapetown/data-portal@sha256:dc2f5a6d18d123c5bcc7eda746a5f97ca56b6acc7dc935b427b705977eeb368b
    volumeMounts:
    - mountPath: "/etc/ckan/production.ini"
      subPath: "production.ini"
      name: production-config
    - mountPath: "/etc/ckan/who.ini"
      subPath: "who.ini"
      name: who-config
    envFrom:
    - secretRef:
        name: ckan-secret
    env:
    - name: "CKAN_SITE_URL"
      value: "https://ds3.capetown.gov.za"
    - name: "CKAN_SOLR_URL"
      value: "http://ckan-solr:8983/solr/ckan"
    - name: "CKAN_REDIS_URL"
      value: "redis://ckan-redis:6379/1"
    - name: "CKAN_DATAPUSHER_URL"
      value: "http://ckan-datapusher:8800/"
    command:
    - "cat"
    args:
    - "/dev/random"
  restartPolicy: Never
  volumes:
    - name: production-config
      configMap:
        name: production-ini
    - name: who-config
      configMap:
        name: who-ini
